/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.*;
import data.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julro
 */
public class telaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form telaProdutos
     */
    public telaProdutos() {
        initComponents();
        preencherTudo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLanches = new javax.swing.JTable();
        lbBebidas = new javax.swing.JLabel();
        lbLanches = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBebidas = new javax.swing.JTable();
        lbSobremesas = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAcompanhamentos = new javax.swing.JTable();
        lbAcompanhamentos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSobremesas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoltar.setBackground(new java.awt.Color(255, 0, 0));
        btnVoltar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblLanches.setFont(new java.awt.Font("sansserif", 0, 8)); // NOI18N
        tblLanches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Ingredientes", "Valor (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLanches);

        lbBebidas.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lbBebidas.setForeground(new java.awt.Color(255, 0, 0));
        lbBebidas.setText("Bebidas");

        lbLanches.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lbLanches.setForeground(new java.awt.Color(255, 0, 0));
        lbLanches.setText("Lanches");

        tblBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Quantidade (ml)", "Valor (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBebidas);

        lbSobremesas.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lbSobremesas.setForeground(new java.awt.Color(255, 0, 0));
        lbSobremesas.setText("Sobremesas");

        tblAcompanhamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Valor (R$)"
            }
        ));
        jScrollPane3.setViewportView(tblAcompanhamentos);

        lbAcompanhamentos.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        lbAcompanhamentos.setForeground(new java.awt.Color(255, 0, 0));
        lbAcompanhamentos.setText("Acompanhamentos");

        tblSobremesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Sabor", "Valor (R$)"
            }
        ));
        jScrollPane4.setViewportView(tblSobremesas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbLanches)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(lbBebidas)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(lbAcompanhamentos)
                                .addComponent(lbSobremesas)))))
                .addGap(462, 462, 462))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbLanches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBebidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAcompanhamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSobremesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbAcompanhamentos;
    private javax.swing.JLabel lbBebidas;
    private javax.swing.JLabel lbLanches;
    private javax.swing.JLabel lbSobremesas;
    private javax.swing.JTable tblAcompanhamentos;
    private javax.swing.JTable tblBebidas;
    private javax.swing.JTable tblLanches;
    private javax.swing.JTable tblSobremesas;
    // End of variables declaration//GEN-END:variables
        
    
    public void preencherTudo(){
        preencherLanches();
        preencherBebidas();
        preencherAc();
        preencherSob();
    }
        
    public void preencherLanches(){
        LancheDAO LDAO = new LancheDAO();
        List<Lanche> listaLanches = LDAO.getLanches();
        DefaultTableModel tabelaLanches = (DefaultTableModel) tblLanches.getModel();
        tabelaLanches.setNumRows(0);
        
        for(Lanche l : listaLanches){
            Object[] obj = new Object[] {
                l.getId_lanche(),
                l.getNome(),
                l.getIngredientes(),
                l.getValor()
            };
            
            tabelaLanches.addRow(obj);
            
        }
    }
    
    public void preencherBebidas(){
        BebidaDAO BDAO = new BebidaDAO();
        List<Bebida> listaBebidas = BDAO.getBebidas();
        DefaultTableModel tabelaBebidas = (DefaultTableModel) tblBebidas.getModel();
        tabelaBebidas.setNumRows(0);
        
        for(Bebida b : listaBebidas){
            Object[] obj = new Object[]{
                b.getId_bebida(),
                b.getNome(),
                b.getQuantidade(),
                b.getValor()
                
            };
            
            tabelaBebidas.addRow(obj);
        }
    }
    
    public void preencherAc(){
        AcompanhamentoDAO AcDAO = new AcompanhamentoDAO();
        List<Acompanhamento> listaAc = AcDAO.getAc();
        DefaultTableModel tabelaAc = (DefaultTableModel) tblAcompanhamentos.getModel();
        tabelaAc.setNumRows(0);
        
        for(Acompanhamento a : listaAc){
            Object[] obj = new Object[]{
                a.getId_acompanhamento(),
                a.getNome(),
                a.getValor()
            
            };
            
            tabelaAc.addRow(obj);
        }
    }
    
    public void preencherSob(){
        SobremesaDAO SDAO = new SobremesaDAO();
        List<Sobremesa> listaS = SDAO.getSob();
        DefaultTableModel tabelaSob = (DefaultTableModel) tblSobremesas.getModel();
        tabelaSob.setNumRows(0);
        
        for(Sobremesa s : listaS){
            Object[] obj = new Object[]{
                s.getId_sobremesa(),
                s.getNome(),
                s.getSabor(),
                s.getValor()
            };
            
            tabelaSob.addRow(obj);
        }
    }
}

